# Site settings
title: "My Serif-Powered Site"
description: "Slick business site with Jekyll Serif"

# Production URLs
url: "https://speedboostco.github.io"    # your GitHub Pages domain
baseurl: "/speedboost-seo-ai"            # the repo name, leading slash, no trailing slash

# Theme
remote_theme: zerostaticthemes/jekyll-serif-theme
plugins:
  - jekyll-remote-theme
